# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-20 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('category', models.CharField(choices=[('Animals', 'Animals'), ('Arts', 'Arts & Culture'), ('Community', 'Community & Family'), ('Education', 'Education'), ('Environment', 'Environment'), ('Disaster', 'Disaster Relief'), ('Health', 'Health & Medical'), ('Human', 'Human Services'), ('Housing', 'Housing')], max_length=254)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
