# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-12 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='price',
        ),
    ]
