# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-26 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200424_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Animals', 'Animals'), ('Arts & Culture', 'Arts & Culture'), ('Community & Family', 'Community & Family'), ('Education', 'Education'), ('Environment', 'Environment'), ('Disaster Relief', 'Disaster Relief'), ('Health & Medical', 'Health & Medical'), ('Human Services', 'Human Services'), ('Housing', 'Housing')], max_length=254),
        ),
    ]
